apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pghero
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pghero
    spec:
      containers:
        - name: pghero
          image: ankane/pghero
          ports:
            - containerPort: 8080
              name: pghero
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: slotlist-backend
                  key: pghero_database_url
            - name: PGHERO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: slotlist-backend
                  key: pghero_username
            - name: PGHERO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: slotlist-backend
                  key: pghero_password