apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: postgres-persistent-storage
  namespace: kube-system
spec:
  capacity:
    storage: "25Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "slotlist-info-postgres-disk"