apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.3-alpine
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: slotlist-backend
                  key: postgres_database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: slotlist-backend
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: slotlist-backend
                  key: postgres_password
      volumes:
        - name: postgres-persistent-storage
          gcePersistentDisk:
            pdName: slotlist-info-postgres-disk
            fsType: ext4