kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.4-alpine
        name: traefik-ingress-lb
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 8080
        args:
        - --consul
        - --consul.endpoint=traefik-consul.kube-system.svc.cluster.local:8500
        env:
        - name: CLOUDFLARE_EMAIL
          valueFrom:
            secretKeyRef:
              name: traefik-cloudflare
              key: email
        - name: CLOUDFLARE_API_KEY
          valueFrom:
            secretKeyRef:
              name: traefik-cloudflare
              key: api_key