version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: slotlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_DATABASE=slotlist
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - CONFIG_JWT_SECRET=development-secret-key-change-in-production
      - CONFIG_JWT_ISSUER=http://localhost:8000
      - CONFIG_JWT_AUDIENCE=http://localhost:8000
      - CONFIG_STEAM_API_SECRET=your-steam-api-key-here
      - DJANGO_SECRET_KEY=development-django-secret-change-in-production
      - ALLOWED_HOSTS=*
    depends_on:
      - db

volumes:
  postgres_data:
