steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/slotlist/backend:latest', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/slotlist/backend:$COMMIT_SHA', '.' ]

images:
  - 'eu.gcr.io/$PROJECT_ID/slotlist/backend:latest'
  - 'eu.gcr.io/$PROJECT_ID/slotlist/backend:$COMMIT_SHA'