# Generated by Django 4.2.25 on 2025-10-16 21:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('game_servers', models.JSONField(blank=True, null=True)),
                ('voice_comms', models.JSONField(blank=True, null=True)),
                ('repositories', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'communities',
                'db_table': 'communities',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('briefing_time', models.DateTimeField(blank=True, null=True)),
                ('slot_list_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('community', 'Community'), ('private', 'Private'), ('hidden', 'Hidden')], default='hidden', max_length=50)),
                ('tech_teleport', models.BooleanField(default=False)),
                ('tech_respawn', models.BooleanField(default=False)),
                ('details_map', models.CharField(blank=True, max_length=255, null=True)),
                ('details_game_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('details_required_dlcs', models.JSONField(blank=True, null=True)),
                ('game_server', models.JSONField(blank=True, null=True)),
                ('voice_comms', models.JSONField(blank=True, null=True)),
                ('repositories', models.JSONField(blank=True, null=True)),
                ('rules_of_engagement', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='api.community')),
            ],
            options={
                'db_table': 'missions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('steam_id', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.community')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionSlotTemplate',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slot_groups', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_templates', to='api.community')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='api.user')),
            ],
            options={
                'db_table': 'missionSlotTemplates',
            },
        ),
        migrations.CreateModel(
            name='MissionSlotGroup',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_groups', to='api.mission')),
            ],
            options={
                'db_table': 'missionSlotGroups',
                'ordering': ['order_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MissionSlot',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('detailed_description', models.TextField(blank=True, default='')),
                ('order_number', models.IntegerField(default=0)),
                ('required_dlcs', models.JSONField(blank=True, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('reserve', models.BooleanField(default=False)),
                ('auto_assignable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_slots', to='api.user')),
                ('restricted_community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_slots', to='api.community')),
                ('slot_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.missionslotgroup')),
            ],
            options={
                'db_table': 'missionSlots',
                'ordering': ['order_number', 'title'],
                'unique_together': {('slot_group', 'assignee')},
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='api.user'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.user')),
            ],
            options={
                'db_table': 'permissions',
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='MissionSlotRegistration',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.missionslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_registrations', to='api.user')),
            ],
            options={
                'db_table': 'missionSlotRegistrations',
                'unique_together': {('user', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='MissionAccess',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_accesses', to='api.community')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='api.mission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_accesses', to='api.user')),
            ],
            options={
                'db_table': 'missionAccesses',
                'unique_together': {('mission', 'community'), ('mission', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommunityApplication',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied')], default='submitted', max_length=50)),
                ('application_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.user')),
            ],
            options={
                'db_table': 'communityApplications',
                'unique_together': {('user', 'community')},
            },
        ),
    ]
